name: Build Application

on:
  workflow_dispatch:
    inputs:
      platform:
        description: '构建平台 (all/mac/win/linux)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - mac
          - win
          - linux

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: macos-latest
            platform: mac
          - os: windows-latest
            platform: win
          - os: ubuntu-latest
            platform: linux
    
    runs-on: ${{ matrix.config.os }}
    
    if: ${{ inputs.platform == 'all' || inputs.platform == matrix.config.platform }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build Application
        run: npm run build:${{ matrix.config.platform }}
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config.platform }}-build
          path: dist/